import { LegalPage } from "@/components/legal/legal-page";

export const metadata = { title: "AI Disclaimer — LynxHire" };

export default function AIDisclaimerPage() {
  return (
    <LegalPage
      title="AI Transparency & Disclaimer"
      effectiveDate="January 1, 2026"
      lastUpdated="March 1, 2026"
      intro="LynxHire uses artificial intelligence to assist in job matching, candidate ranking, and job description generation. This page explains how AI is used, its limitations, and your rights."
      sections={[
        {
          heading: "1. How We Use AI",
          content: [
            "Job Matching: Our AI analyzes candidate profiles (skills, experience, work authorization, location, salary expectations) and compares them against job requirements to generate a match score (0–100%).",
            "Job Description Generation: Employers may use our AI assistant, powered by Anthropic Claude, to draft job descriptions from bullet points. All AI-generated content is editable and subject to employer review.",
            "Candidate Recommendations: Employers may see AI-ranked candidate lists based on match scores.",
            "All AI features are powered by Anthropic's Claude API and operate entirely server-side.",
          ],
        },
        {
          heading: "2. Informational Use Only",
          content:
            "AI-generated match scores, recommendations, and rankings are provided for informational purposes only. They do not constitute professional, legal, employment, or hiring advice. LynxHire AI outputs are statistical predictions based on the data provided and should not be the sole basis for any hiring or employment decision.",
        },
        {
          heading: "3. No Bias Guarantee",
          content:
            "While we implement technical and procedural measures to reduce algorithmic bias in our AI systems, we cannot guarantee that automated outputs are free from errors, bias, or unintended outcomes. Factors including but not limited to data quality, historical patterns in training data, and the inherent limitations of statistical models may affect outputs.",
        },
        {
          heading: "4. Human Decision Responsibility",
          content:
            "Employers are solely responsible for all hiring decisions made using this Platform. Candidates are solely responsible for the accuracy of information they submit. LynxHire is not responsible for any employment outcome, dispute, or decision that results from the use of AI features on this Platform.",
        },
        {
          heading: "5. No Discrimination by Design",
          content: [
            "Our AI matching does not use protected characteristics (race, gender, age, religion, national origin, disability) as ranking factors.",
            "We prohibit job postings that explicitly or implicitly discriminate based on protected characteristics under the Canadian Human Rights Act.",
            "We conduct periodic reviews of AI outputs to identify and mitigate unintended discriminatory patterns.",
          ],
        },
        {
          heading: "6. Explainability",
          content:
            "Users may request general information about how their AI match scores were generated by contacting support@lynxhire.ca. We will provide a plain-language explanation of the primary factors that influenced the score. We do not disclose proprietary model weights or algorithmic details.",
        },
        {
          heading: "7. AI Model Information",
          content:
            "LynxHire's AI features are powered by Anthropic Claude (claude-sonnet series). Anthropic's usage policies apply to all AI interactions. LynxHire does not train custom models on candidate personal data. AI outputs are generated at the time of request and not permanently stored beyond what is necessary for platform operation.",
        },
        {
          heading: "8. Opt-Out",
          content:
            "Candidates who do not wish to be scored by AI matching may contact support@lynxhire.ca to request manual-only processing. Note that opting out of AI matching may significantly reduce the discoverability of your profile to employers.",
        },
        {
          heading: "9. Continuous Improvement",
          content:
            "We review our AI systems regularly and update policies to reflect advances in AI governance, Canadian regulatory guidance, and industry best practices. Material changes to our AI use will be communicated via the Privacy Policy update process.",
        },
        {
          heading: "10. Contact",
          content:
            "Questions about AI use: legal@lynxhire.ca\nTo request AI explainability information: support@lynxhire.ca",
        },
      ]}
    />
  );
}
